#!/bin/sh
# install-decoy.sh — put a plausible page at the tunnel's public hostname.
#
# A host that answers 404, or an obvious reverse proxy banner, is a signal.
# This serves an ordinary static page at "/" and forwards only the secret
# WebSocket path to sing-box, so a browser, a scanner or a curious middlebox
# finds a boring site and never reaches the inbound.
#
# Run it ON the Nginx Proxy Manager host. Re-run it whenever the page or the
# path changes — it is idempotent.
#
#   DOMAIN=cdn.example.com \
#   WS_PATH=/0f3a… \
#   UPSTREAM=10.0.0.4:8081 \
#     sh install-decoy.sh
#
# WHY YOU WILL NEED IT AGAIN: Nginx Proxy Manager regenerates a host's conf
# from its database every time that host is saved in the UI. Anything added by
# hand — including the WebSocket location, so the tunnel itself — is dropped.
# Run this script again after any change to the host in NPM.

set -eu

DOMAIN="${DOMAIN:-}"
WS_PATH="${WS_PATH:-}"
UPSTREAM="${UPSTREAM:-}"
SITE_DIR="${SITE_DIR:-/data/nginx/decoy}"
CONF_DIR="${CONF_DIR:-/data/nginx/proxy_host}"
LOCATIONS="$SITE_DIR/locations.conf"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { printf "${GREEN}[+]${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}[!]${NC} %s\n" "$*"; }
error() { printf "${RED}[x]${NC} %s\n" "$*"; exit 1; }

# ── Steps ────────────────────────────────────────────────────────────────────

check_args() {
  [ "$(id -u)" -eq 0 ] || error "a lancer en root"
  [ -n "$DOMAIN" ]   || error "DOMAIN manquant (ex: cdn.example.com)"
  [ -n "$WS_PATH" ]  || error "WS_PATH manquant (le chemin secret, ex: /0f3a…)"
  [ -n "$UPSTREAM" ] || error "UPSTREAM manquant (ex: 10.0.0.4:8081)"
  case "$WS_PATH" in /*) ;; *) error "WS_PATH doit commencer par /" ;; esac
  [ -d "$CONF_DIR" ] || error "hote Nginx Proxy Manager attendu : $CONF_DIR introuvable"
}

write_page() {
  mkdir -p "$SITE_DIR"
  cat > "$SITE_DIR/index.html" <<'HTML'
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Static Asset Delivery</title>
<style>
  :root { color-scheme: light dark; }
  body {
    margin: 0; min-height: 100vh; display: flex; align-items: center; justify-content: center;
    font: 15px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    background: #fafafa; color: #333;
  }
  main { max-width: 30rem; padding: 2rem; }
  h1 { font-size: 1.15rem; font-weight: 600; margin: 0 0 .75rem; letter-spacing: -.01em; }
  p { margin: 0 0 .6rem; color: #666; }
  code { background: #f0f0f0; padding: .1rem .35rem; border-radius: 3px; font-size: .9em; }
  footer { margin-top: 1.5rem; font-size: .82rem; color: #999; }
  @media (prefers-color-scheme: dark) {
    body { background: #16181a; color: #d6d6d6; }
    p { color: #9a9a9a; }
    code { background: #24272a; }
    footer { color: #6d6d6d; }
  }
</style>
</head>
<body>
<main>
  <h1>Static asset delivery</h1>
  <p>This host serves cached static resources. There is no browsable index.</p>
  <p>Assets are addressed directly by path, for example <code>/assets/&lt;hash&gt;</code>.</p>
  <footer>If you reached this page by mistake, no action is required.</footer>
</main>
</body>
</html>
HTML
  info "Page ecrite dans $SITE_DIR/index.html"
}

write_locations() {
  # Kept in our own file rather than inline in the vhost: the only edit to the
  # NPM-generated conf is then a single include line, easy to put back.
  cat > "$LOCATIONS" <<EOF
# Generated by install-decoy.sh — do not edit, re-run the script instead.

# The secret path, and only it, reaches sing-box.
location $WS_PATH {
  proxy_pass http://$UPSTREAM;
  proxy_set_header Host \$host;
  proxy_set_header X-Real-IP \$remote_addr;
  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
  proxy_set_header Upgrade \$http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_http_version 1.1;
  # A tunnel is long-lived: do not cut it after the default 60 seconds.
  proxy_read_timeout 86400s;
  proxy_send_timeout 86400s;
}

# Everything else is the cover page. sing-box is never reached.
location / {
  root $SITE_DIR;
  index index.html;
  try_files \$uri \$uri/ /index.html;
}
EOF
  info "Blocs location ecrits dans $LOCATIONS"
}

patch_vhost() {
  conf=$(grep -ls "server_name .*${DOMAIN}" "$CONF_DIR"/*.conf 2>/dev/null | head -1 || true)
  [ -n "${conf:-}" ] || error "aucun vhost pour $DOMAIN dans $CONF_DIR — le creer dans NPM d'abord"

  if grep -q "include $LOCATIONS;" "$conf"; then
    info "Vhost deja relie : $(basename "$conf")"
    return
  fi

  # NPM may have left its own hand-added locations behind; ours take over, and
  # two `location /` blocks in one server would make nginx refuse to start.
  if grep -qE '^\s*location\s+/\s*\{' "$conf"; then
    warn "$(basename "$conf") contient deja un 'location /' — le retirer a la main"
    warn "puis relancer ce script, sinon nginx refusera de demarrer"
    error "abandon avant de casser la configuration"
  fi

  cp "$conf" "$conf.bak"
  # Insert before the last closing brace, i.e. inside the server block.
  awk -v inc="  include $LOCATIONS;" '
    { lines[NR] = $0 }
    /^}/ { last = NR }
    END {
      for (i = 1; i <= NR; i++) {
        if (i == last) print inc
        print lines[i]
      }
    }
  ' "$conf.bak" > "$conf"
  info "Include ajoute dans $(basename "$conf") (copie : $(basename "$conf").bak)"
}

reload_nginx() {
  nginx -t >/dev/null 2>&1 || {
    nginx -t || true
    error "configuration nginx invalide — rien n'a ete recharge"
  }
  nginx -s reload
  info "nginx recharge"
}

# ── Run ──────────────────────────────────────────────────────────────────────

check_args
write_page
write_locations
patch_vhost
reload_nginx

echo
info "Page de couverture active sur https://$DOMAIN/"
echo "    chemin tunnel : $WS_PATH -> $UPSTREAM"
echo
echo "  A relancer apres toute modification de l'hote dans l'interface NPM :"
echo "  NPM regenere le vhost depuis sa base et supprime l'include."
echo
